version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
          time: '02:00'
      target-branch: 'main'
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
          time: '03:00'
      target-branch: 'main'
    - package-ecosystem: 'devcontainers'
      directory: '/'
      schedule:
          interval: 'weekly'
      target-branch: 'main'
